apiVersion: 1

datasources:
- name: influxdb
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb.monitoring:8086
  database: influxdb
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: readonly
  basicAuthPassword: readonly